image: cangol/android-gradle
stages:
  - build
  - test
build:
  stage: build
  script:
    - cp app/mock-google-services.json app/google-services.json
    - gradlew build
    - gradlew test

  tags:
    - android
